/*
 *
 * DQMCanvas.h header template automatically generated by a class generator
 * Creation date : mar. oct. 13 2015
 *
 * This file is part of DQM4HEP libraries.
 * 
 * DQM4HEP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * DQM4HEP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with DQM4HEP.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */


#ifndef DQMCANVAS_H
#define DQMCANVAS_H

// -- qt headers
#include <QMdiSubWindow>
#include <QCloseEvent>

#include "dqm4hep/DQM4HEP.h"

namespace dqm4hep
{

class DQMMonitoring;
class DQMGuiMonitorElement;
class DQMRootWidget;

/** DQMCanvas class
 */ 
class DQMCanvas : public QMdiSubWindow
{
	Q_OBJECT

public:
	/** Constructor
	 */
	DQMCanvas(DQMMonitoring *pMonitoring);

	/** Destructor
	 */
	virtual ~DQMCanvas();

	/** Get the monitoring instance
	 */
	DQMMonitoring *getMonitoring() const;

	/** Get the monitor element currently drawn
	 */
	DQMGuiMonitorElement *getCurrentMonitorElement() const;

	/** Get the embedded root widget
	 */
	DQMRootWidget *getRootWidget() const;

public slots:
	/** Draw the monitor element on the root widget
	 */
	void draw(DQMGuiMonitorElement *pMonitorElement);

protected:

	DQMMonitoring         *m_pMonitoring;
	DQMRootWidget         *m_pRootWidget;
};

} 

#endif  //  DQMCANVAS_H
