  /// \file DQMLoggerWidget.h
/*
 *
 * DQMLoggerWidget.h header template automatically generated by a class generator
 * Creation date : jeu. mai 7 2015
 *
 * This file is part of DQM4HEP libraries.
 * 
 * DQM4HEP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * DQM4HEP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with DQM4HEP.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */


#ifndef DQMLOGGERWIDGET_H
#define DQMLOGGERWIDGET_H

// -- dqm4hep headers
#include "dqm4hep/DQM4HEP.h"
#include "dqm4hep/DQMLogger.h"

// -- qt headers
#include <QGroupBox>
#include <QColor>
#include <QTextEdit>

namespace dqm4hep
{

/** DQMLoggerWidget class
 */ 
class DQMLoggerWidget : public DQMLogger, public QGroupBox
{
public:

	/** Constructor
     */
	DQMLoggerWidget(QWidget *pParent = 0);

	/** Log a message with the default level (MESSAGE)
	 */
	void log(const std::string &message);

	/** Log a message with a log level
	 */
	void log(LogLevel level, const std::string &message);

private:

	Qt::GlobalColor getColor(LogLevel level) const;
	std::string getLogMessageHead(LogLevel level) const;
	QTextEdit                        *m_pLoggingWidget;       ///< the text widget used for logging
}; 

} 

#endif  //  DQMLOGGERWIDGET_H
