  /// \file DQMMonitoring.h
/*
 *
 * DQMMonitoring.h header template automatically generated by a class generator
 * Creation date : sam. oct. 10 2015
 *
 * This file is part of DQM4HEP libraries.
 * 
 * DQM4HEP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * DQM4HEP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with DQM4HEP.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */


#ifndef DQMMONITORING_H
#define DQMMONITORING_H

// -- dqm4hep headers
#include "dqm4hep/DQM4HEP.h"

namespace dqm4hep
{

class DQMMonitoringController;
class DQMMonitoringModel;
class DQMMonitoringView;

/** DQMMonitoring class
 */
class DQMMonitoring
{
public:
	/** Constructor
	 */
	DQMMonitoring();

	/** Destructor
	 */
	virtual ~DQMMonitoring();

	/** Set the monitoring controller
	 */
	void setController(DQMMonitoringController *pController);

	/** Get the monitoring controller
	 */
	DQMMonitoringController *getController() const;

	/** Set the monitoring model
	 */
	void setModel(DQMMonitoringModel *pModel);

	/** Get the monitoring model
	 */
	DQMMonitoringModel *getModel() const;

	/** Set the monitoring view
	 */
	void setView(DQMMonitoringView *pView);

	/** get the monitoring controller
	 */
	DQMMonitoringView *getView() const;

protected:

	DQMMonitoringController         *m_pController;       ///< The monitoring controller
	DQMMonitoringModel              *m_pModel;             ///< The monitoring model
	DQMMonitoringView               *m_pView;              ///< The monitoring view
}; 

} 

#endif  //  DQMMONITORING_H
