  /// \file DQMJobInterface.cc
/*
 *
 * DQMJobInterface.cc source template automatically generated by a class generator
 * Creation date : dim. janv. 10 2016
 *
 * This file is part of DQM4HEP libraries.
 * 
 * DQM4HEP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * DQM4HEP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with DQM4HEP.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */


#include "dqm4hep/vis/DQMJobInterface.h"

namespace dqm4hep
{

DQMJobInterface::DQMJobInterface() :
		DimJobInterface(),
		m_started(false)
{
	/* nop */
}

//-------------------------------------------------------------------------------------------------

DQMJobInterface::~DQMJobInterface() 
{
	/* nop */
}

//-------------------------------------------------------------------------------------------------

bool DQMJobInterface::started() const
{
	return m_started;
}

//-------------------------------------------------------------------------------------------------

void DQMJobInterface::startUpdate(int nSeconds)
{
	if(m_started)
		DimJobInterface::stopTimer();

	DimJobInterface::startTimer(nSeconds);
	m_started = true;
}

//-------------------------------------------------------------------------------------------------

void DQMJobInterface::stopUpdate()
{
	if(m_started)
		DimJobInterface::stopTimer();

	m_started = false;
}

//-------------------------------------------------------------------------------------------------

void DQMJobInterface::statusReceived(const std::string &hostName)
{
	emit statusReceived(QString(hostName.c_str()));
}


} 

